# Generated by Django 4.0.1 on 2022-02-08 19:04

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_image_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='facedata',
            field=picklefield.fields.PickledObjectField(default=None, editable=False),
        ),
    ]
