# Generated by Django 4.0.1 on 2022-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='Elective',
            field=models.CharField(choices=[('1', 'Vacuum'), ('2', 'Optics')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='custom',
            name='branch',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='custom',
            name='course',
            field=models.CharField(choices=[('1', 'PHD'), ('2', 'B-Tech'), ('3', 'MSc'), ('4', 'M-Tech')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='custom',
            name='department',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='year',
            field=models.CharField(max_length=8),
        ),
    ]
